import{a as v,S as w,i as a}from"./assets/vendor-DQvd0HNi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const S="https://pixabay.com/api/",q="55162461-6dc934a4c197e0b77d4d693df";async function f(o,t=1){return(await v.get(S,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const m=document.querySelector(".gallery"),l=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new w(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const t=o.map(({webformatURL:s,largeImageURL:c,tags:e,likes:r,views:i,comments:b,downloads:L})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${b}</p>
          <p><b>Downloads:</b> ${L}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",t),B.refresh()}function M(){m.innerHTML=""}function g(){l&&l.classList.add("is-visible")}function p(){l&&l.classList.remove("is-visible")}function P(){y.classList.remove("is-hidden")}function u(){y.classList.add("is-hidden")}const $=document.querySelector(".form"),E=document.querySelector(".load-more");let d="",n=1;$.addEventListener("submit",O);E.addEventListener("click",x);async function O(o){o.preventDefault();const t=o.target.elements["search-text"].value.trim();if(!t){a.warning({message:"Please enter a search query!"});return}d=t,n=1,M(),u(),g();try{const s=await f(d,n);if(s.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(s.hits),n*15>=s.totalHits?(u(),a.info({message:"We're sorry, but you've reached the end of search results."})):P()}catch{a.error({message:"Something went wrong. Try again later!"})}finally{p()}}async function x(){n+=1,g();try{const o=await f(d,n);h(o.hits);const t=document.querySelector(".gallery-item");if(t){const{height:s}=t.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}n*15>=o.totalHits&&(u(),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({message:"Error loading more images!"})}finally{p()}}
//# sourceMappingURL=index.js.map
