import{a as w,S,i as a}from"./assets/vendor-DQvd0HNi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const q="https://pixabay.com/api/",B="55162461-6dc934a4c197e0b77d4d693df";async function m(o,t=1){return(await w.get(q,{params:{key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const y=document.querySelector(".gallery"),l=document.querySelector(".loader"),h=document.querySelector(".load-more"),M=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const t=o.map(({webformatURL:s,largeImageURL:c,tags:e,likes:r,views:i,comments:L,downloads:v})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${L}</p>
          <p><b>Downloads:</b> ${v}</p>
        </div>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",t),M.refresh()}function P(){y.innerHTML=""}function p(){l&&l.classList.add("is-visible")}function b(){l&&l.classList.remove("is-visible")}function u(){h.classList.remove("is-hidden")}function d(){h.classList.add("is-hidden")}const $=document.querySelector(".form"),E=document.querySelector(".load-more");let f="",n=1;$.addEventListener("submit",O);E.addEventListener("click",x);async function O(o){o.preventDefault();const t=o.target.elements["search-text"].value.trim();if(!t){a.warning({message:"Please enter a search query!"});return}f=t,n=1,P(),d(),p();try{const s=await m(f,n);if(s.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}g(s.hits),n*15>=s.totalHits?(d(),a.info({message:"We're sorry, but you've reached the end of search results."})):u()}catch{a.error({message:"Something went wrong. Try again later!"})}finally{b()}}async function x(){n+=1,d(),p();try{const o=await m(f,n);g(o.hits);const t=document.querySelector(".gallery-item");if(t){const{height:s}=t.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}n*15>=o.totalHits?a.info({message:"We're sorry, but you've reached the end of search results."}):u()}catch{a.error({message:"Error loading more images!"}),u()}finally{b()}}
//# sourceMappingURL=index.js.map
